### PR TITLE
updating kepler_solver function name

### PR DESCRIPTION
**Pull request by olehmer**
The ! in the function name indicates that the function will modify the input parameters. This is not the case for this function (Julia doesn't allow you to modify floats as they are immutable). The ! should be used on functions that take mutable arguments (like arrays) and modify the array itself. Adding the ! doesn't provide a speedup (it is only a naming convention), the speedup comes from the implementation.

### CODE REVIEW

**Comment by jlustigy** [comment]
This is a very good point. My worry is that this merge will change how kepler_solve is called, and everyone will need to change it in their hw2 code. But maybe that's ok?

**Comment by olehmer** [comment]
That's probably a good call, it's not really a high priority issues

**Comment by jlustigy** [comment]
I've held off on this because of how it will change the name of kepler_solve and I know (from personal experience) that people are working hard to finish up for tomorrow and I don't want to introduce a bug somewhere that should be "stable". However once everyone submits pull requests, I (or Eric) can swoop in and make this change in everyone's code. 

Thus, I will merge this pull request when everyone has submitted HW2. Or, you can retract your change to kepler_solve (not quite sure how this is done) so that I can merge just your hw2. 

All in all, Owen, you seem to be right about the use of "!" in function names.

**Comment by jlustigy** [comment]
I just merged this on the command line. @olehmer, fetch to make sure everything is up-to-date and submit another pull request if you have changes to add.

**Pull request closed without merging**
